# Copyright 2022 DARWIN EU (C)
#
# This file is part of CohortCharacteristics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create a visual table from the output of summariseCohortCount.
#' `r lifecycle::badge("experimental")`
#'
#' @param result A summarised_result object generated by summariseCohortCount().
#' @param header Columns to use as headers.
#' @param groupColumn Columns to use to group.
#' @param type Whether a 'gt' or 'flextable' should be created.
#'
#' @return A visual table.
#'
#' @export
#'
#' @examples
#' \donttest{
#' library(CohortCharacteristics)
#'
#' cdm <- mockCohortCharacteristics()
#'
#' cdm$cohort2 |>
#'   summariseCohortCount() |>
#'   tableCohortCount()
#' }
#'
tableCohortCount <- function(result,
                             header = "cdm_name",
                             groupColumn = "cohort_name",
                             type = "gt") {
  # initial checks
  assertClass(result, "summarised_result")
  assertChoice(type, c("gt", "flextable"), length = 1)
  assertChoice(header, c("cdm_name", "cohort_name"))
  assertChoice(groupColumn, c("cdm_name", "cohort_name"))

  header <- correct(header)
  groupColumn <- correct(groupColumn)

  # create table
  result <- result |>
    visOmopResults::filterSettings(.data$result_type == "cohort_count") |>
    visOmopResults::splitAll() |>
    dplyr::select(-c(
      "result_id", "variable_level", "estimate_name", "estimate_type"
    )) |>
    dplyr::rename(
      "Variable" = "variable_name",
      "CDM name" = "cdm_name",
      "Cohort name" = "cohort_name"
    ) |>
    visOmopResults::formatHeader(header = header)

  if (type == "gt") {
    result <- result |>
      visOmopResults::gtTable(groupNameCol = groupColumn)
  } else if (type == "flextable") {
    result <- result |>
      visOmopResults::fxTable(groupNameCol = groupColumn)
  }

  return(result)
}

correct <- function(x) {
  x[x == "cdm_name"] <- "CDM name"
  x[x == "cohort_name"] <- "Cohort name"
  return(x)
}
